export enum ESECTION {
	HEADER = 'header',
	MAIN = 'main',
	DESCRIPTION = 'description',
	STAGES = 'stages',
	RESULTS = 'results',
	PROBLEMS = 'problems',
	PRIZE = 'prize',
	REASONS = 'reasons',
	INVITE = 'invite',
	FAQ = 'faq',
	PARTNERS = 'partners',
	DOCUMENT = 'document',
	FOOTER = 'footer',
}
